// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],

  mySidebar: [
    {
      type: 'category',
      label: 'Namaste JS Season 1', // The label for the category in the sidebar
      items: Array.from({ length: 19 }, (_, index) => `lecture-${index + 1}`), // Generate the list of lecture items
    },
    {
      type: 'category',
      label: 'Namaste JS Season 2', // The label for the category in the sidebar
      items: Array.from({ length: 3 }, (_, index) => `lecture-${index + 20}`), // Generate the list of lecture items
    },
  ],
};

module.exports = sidebars;
